### ISSUE TITLE
Incorrect behavior for blue critters in Grasstown

### ISSUE THREAD

**Issue by ajerijian** [libretro/nxengine-libretro#20]
OS: Linux Mint 17.2
RetroArch version: 1.2.2
nxengine-libretro version: 1.0.0.4

In the original Cave Story game and Cave Story+, the blue critters in Grasstown (Bushlands) attempt to approach the main character by spinning their ears like helicopter blades and stomping the ground where the player is standing.

In nxengine-libretro, the blue critters simply hop at a short distance without shaking the ground.  This affects gameplay by reducing the challenge of getting through the first part of Grasstown.

**Comment by fr500** [comment]
Have you tried with standalone nxengine? might be an upstream issue

**Comment by ajerijian** [comment]
I tried this with the original NXEngine (version 1.0.0.6) and it's definitely an upstream issue as well.
