### ISSUE TITLE
Weapon does not select from menu with the menu button

### ISSUE THREAD

**Issue by ghost** [libretro/nxengine-libretro#21]
OS: Linux Mint 17.2
RetroArch version: 1.2.2
nxengine-libretro version: 1.0.0.4

Steps to reproduce:
1. Have two or more weapons in the player's inventory.
2. Enter the menu using the menu button.
3. Select a different weapon.
4. Press the menu button again to leave the menu.

Instead of selecting the new weapon, the previous weapon remains selected.  A new weapon may be selected from the menu only by using the fire or jump buttons, but this causes a side effect of leaving the menu and performing the fire or jump action, which affects gameplay especially during boss fights.

**Comment by fr500** [comment]
Have you tried with standalone nxengine? might be an upstream issue

**Comment by ajerijian** [comment]
I checked with the latest upstream (NXEngine 1.0.0.6) - in this version, pressing the menu button a second time does not leave the menu screen.
