### ISSUE TITLE
Save files should be at Save Dir

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/nxengine-libretro#28]
For consistency, the saves should be placed in the Save Dir. Right now it's saving at Data/ folder of Cave Story.

**Comment by RobLoach** [comment]
Confirmed.

**Comment by RobLoach** [comment]
This hath been merged. Feel free to close'r up!

**Comment by sergiobenrocha2** [comment]
Nice, and it copied profile.dat from cave story dir. Thanks!
