### ISSUE TITLE
Visual glitch while fighting Misery.

### ISSUE THREAD

**Issue by ClockworkTomato** [libretro/nxengine-libretro#34]
I'm on the latest stable version of Retroarch, and installed the nxengine core from the updater a couple of weeks ago.

The game works flawlessly, the only issue I've had is the following: the Misery boss fight starts properly...

![bug_report_1](https://user-images.githubusercontent.com/24359833/27235739-45af1570-52c2-11e7-9cdb-b60fc1e82d5c.png)

As you can see I drew a red circle around a block; after a while, Misery will try to drop a block just like that one above the player. After she does so, her sprite gets replaced by the one you can see in the next picture:

![bug_report_2](https://user-images.githubusercontent.com/24359833/27235791-80126bc2-52c2-11e7-8e68-a100ec984346.png)

That block I circled is, in fact, Misery. The difference is only aesthetic, as she'll keep fighting and taking damage as usual; sometimes during her attacks (when she'd otherwise be raising her arms) the block sprite will glitch out, but otherwise the fight can go on normally, with Misery reverting to her normal sprite as soon as her health bar is depleted.

**Comment by RobLoach** [comment]
Could you send your save game? I'd be willing to test this out.

**Comment by ClockworkTomato** [comment]
Here's the save; if you start in a small prefab building it's the correct one.

[save.zip](https://github.com/libretro/nxengine-libretro/files/1082499/save.zip)

And, just in case, here's a pic from the title screen:

![untitled](https://user-images.githubusercontent.com/24359833/27252389-9da2887a-535d-11e7-99be-ecad08ac607d.png)

If it wasn't obvious, I'm using the English Aeon Genesis translation.

**Comment by RobLoach** [comment]
Yup, confirmed on latest on Linux Ubuntu 16.04.

**Comment by fr500** [comment]
can you guys bisect?

**Comment by RobLoach** [comment]
Confirmed fixed in https://github.com/libretro/nxengine-libretro/pull/36 . Can close. Nicely done, @andwn .

**Comment by ClockworkTomato** [comment]
Thank you guys!
