### ISSUE TITLE
Cutscene retrigger during first Balrog fight

### ISSUE THREAD

**Issue by FayneAldan** [libretro/nxengine-libretro#41]
I found a cutscene retrigger bug. During the fight with Balrog (or simply in the room if you say you don't want to fight), if you press down where Sue was before taken away by Misery, you'll talk to her again and retrigger the cutscene.
![](https://i.imgur.com/KNfUQHm.png)
![](https://i.imgur.com/ibWR0xv.png)
![](https://i.imgur.com/XRPycTn.png)
![](https://i.imgur.com/kDhpn0o.png)
![](https://i.imgur.com/OoqyOQU.png)

**Comment by isage** [comment]
That's a bug in misery bubble ai. It should remove original Toroko, not just make her invisible.
See https://github.com/isage/nxengine-evo/commit/41ed2d6ec8659087992a9e406307f0cca4d560aa

**Comment by Darknior** [comment]
Thanks for this fix

**Comment by FayneAldan** [comment]
Apologies for the bump, but this issue is still not fixed.
