### ISSUE TITLE
Controller mapping doesn't work correctly.

### ISSUE THREAD

**Issue by andrewtoups** [libretro/nxengine-libretro#72]
I'm running retroarch on Windows 10. Using a dualshock 4. No matter what key the square button is bound too, it also triggers the X button binding.

For example, with this configuration:
* Cross (btn), (Key: z) is set to "jump"
* Square (btn), (Key: a) is set to "fire"

In gameplay, pressing square will fire and jump simultaneously as if both keys are being pressed at once.

Changing either to any other command results in the square button triggering both actions simultaneously. This does not seem to be the case for any other buttons.

I don't have any other types of controllers handy to test unfortunately, but I can verify that the issue is not with my dualshock 4 as it works fine with other cores and games.

**Comment by hizzlekizzle** [comment]
Hmm, I'm not able to reproduce this behavior in Linux. Remapping 'fire' to retropad-Y works fine here without triggering any additional actions.

**Comment by crocket** [comment]
What is your input driver?

**Comment by andrewtoups** [comment]
It turns out it was an issue with the way I had my controller configured! I've closed the issue, sorry for the trouble.
